application: rpcapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /PostService.*
  script: services.app

- url: /.*
  script: rpcapp.app

